# Generated by Django 5.1.4 on 2024-12-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendar_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='owner',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Açıklama girilmemiş'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
