# Generated by Django 5.1.4 on 2024-12-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_calendar_created_at_remove_calendar_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendar'),
            preserve_default=False,
        ),
    ]
