# Generated by Django 5.1.4 on 2024-12-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_alter_event_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
