# Generated by Django 5.1.4 on 2024-12-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.CharField(choices=[('Güz', 'Güz'), ('Bahar', 'Bahar')], default='Güz', max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
