# Generated by Django 5.1.4 on 2024-12-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_event_semester_alter_event_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_date_guz',
        ),
        migrations.RemoveField(
            model_name='event',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date_bahar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_bahar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_guz',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
