# Generated by Django 5.1.4 on 2024-12-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_rename_end_date_event_end_date_guz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date_guz',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date_guz',
            new_name='start_date',
        ),
    ]
